config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/admin_add'

  resources :categories do
    resources :photos
  end

  SengProjectNemo::Application.routes.draw do
  get 'static_pages/admin_add'

    resources :authors
  end

  resources :author_sessions, only: [ :new, :create, :destroy ]

  get 'login'  => 'author_sessions#new'
  get 'logout' => 'author_sessions#destroy'
  get 'static_pages/buy'
  get 'static_pages/resume'
  get 'static_pages/contact'
  get 'static_pages/adminhome'
  get 'static_pages/photo_list'
  get 'static_pages/article_list'
  resources :videos
resources :photos
  root 'welcome#index'
  resources :articles

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  def to_param
    category
  end
  belongs_to :category
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: [:show, :edit, :update, :destroy]

  # GET /photos
  # GET /photos.json
  def index
    @photos = Photo.all
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
    @photo = Photo.find(params[:id])
  end

  # GET /photos/new
  def new
    @photo = Photo.new
  end

  # GET /photos/1/edit
  def edit
  end

  # POST /photos
  # POST /photos.json
  def create
    @photo = Photo.new(photo_params)
    @photo.category = params[:category]

    respond_to do |format|
      if @photo.save
        format.html { redirect_to @photo, notice: 'Photo was successfully created.' }
        format.json { render :show, status: :created, location: @photo }
      else
        format.html { render :new }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /photos/1
  # PATCH/PUT /photos/1.json
  def update
    respond_to do |format|
      if @photo.update(photo_params)
        format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
        format.json { render :show, status: :ok, location: @photo }
      else
        format.html { render :edit }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo.destroy
    respond_to do |format|
      format.html { redirect_to static_pages_adminhome_path, notice: 'Photo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo
      @photo = Photo.find_by_category_id(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def photo_params
      params.require(:photo).permit(:title, :post_time, :description, :category_id)
    end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/photos/_form.html.erb
<style>
    .box {
        width:300px;
        height:300px;
        position:fixed;
        margin-left:-150px; /* half of width */
        margin-top:-150px;  /* half of height */
        top:50%;
        left:50%;
    }
</style>

<table class="box" align="center" width="500px" top="300px">

  <tr><td><h1 style="color:powderblue">Fotoğraf Ekle</h1>
    <%= form_for(@photo) do |f| %>
        <% if @photo.errors.any? %>

            <div id="error_explanation">
              <h2><%= pluralize(@photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

              <ul>
                <% @photo.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
              </ul>
            </div>
        <% end %></td></tr>

        <tr><td>
          <div class="field">

            <%= f.label "Başlık" %><br>
            <%= f.text_field :title %>
          </div></td></tr>
        <tr><td><div class="field">
          <%= f.label "Kategori" %><br>
          <%= collection_select(:photo,:category_id,Category.all,:id,:title) %>

        </div></td></tr>

        <tr><td><div class="field">
          <%= f.label "Resim yükle" %>
          <%= f.file_field :picture %>
        </div></td></tr>
        <tr><td><div class="actions">
          <%= f.submit %>
        </div></td></tr>
        </table>
    <% end %>

app/views/photos/edit.html.erb
<h1>Editing photo</h1>

<%= render 'form' %>

<%= link_to 'Show', @photo %> |
<%= link_to 'Back', photos_path %>

app/views/photos/index.html.erb
<%= render :partial => "common/header" %>

<table align="center" style="margin-top: 30px;" >

<tr>
  <% i=1 %>
  <% @photos.each do |photo| %>

      <td style="padding-left: 20px;padding-bottom: 20px;">
        <a href="/photos/<%= photo.category %>"><img alt="" src="/assets/<%= photo.id %>.png" /></a>
        <p><a href=""><%= photo.category %></a></p>
      </td>

      <% if i % 4 == 0 %>
        </tr>
        <tr>
      <% end %>
      <% i += 1 %>
<% end %>
</tr>

</table>

app/views/photos/new.html.erb
<%= render :partial => "static_pages/panel" %>
<div style="margin-left:100px;margin-top:60px;">


  <%= render 'form' %>

  <%= link_to 'Back', photos_path %>
</div>

app/views/photos/show.html.erb
<%= render :partial => "common/header" %>
<p id="notice"><%= notice %></p>

<table align="center" style="margin-top: 30px;" >

  <tr>
    <% i=1 %>
    <% @photo.each do |photo| %>

        <td style="padding-left: 20px;padding-bottom: 20px;">
          <img alt="" src="/assets/<%= photo.id %>.png" />
        </td>

        <% if i % 4 == 0 %>
            </tr>
            <tr>
        <% end %>
        <% i += 1 %>
    <% end %>
    </tr>

    </table>

<p>
  <strong>Title:</strong>
  <%= @photo.title %>
</p>

<p>
  <strong>Post time:</strong>
  <%= @photo.post_time %>
</p>

<p>
  <strong>Description:</strong>
  <%= @photo.description %>
</p>

<%= link_to 'Edit', edit_photo_path(@photo) %> |
<%= link_to 'Back', photos_path %>