config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/admin_add'

  resources :categories do
    resources :photos
  end

  SengProjectNemo::Application.routes.draw do
  get 'static_pages/admin_add'

    resources :authors
  end

  resources :author_sessions, only: [ :new, :create, :destroy ]

  get 'login'  => 'author_sessions#new'
  get 'logout' => 'author_sessions#destroy'
  get 'static_pages/buy'
  get 'static_pages/resume'
  get 'static_pages/contact'
  get 'static_pages/adminhome'
  get 'static_pages/photo_list'
  get 'static_pages/article_list'
  resources :videos
resources :photos
  root 'welcome#index'
  resources :articles

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :photos
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @photo = Photo.new
    @photo.category_id = @category.id
#    @category = Category.find(params[:id])
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:title)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/_photo.html.erb
<!--<td style="padding-left: 20px;padding-bottom: 20px;">-->

  <a href="/assets/<%= photo.category_id %>/<%= photo.id %>.png">
    <img style="margin-top:5px;" src="/assets/<%= photo.category_id %>/<%= photo.id %>.png" height="150px;" />
  </a>
<!--</td>-->

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<%= render :partial => "common/header" %>



<table align="center" style="margin-top: 30px;" id="categoryTable">

  <tr>
    <% i=1 %>
    <% @categories.each do |category| %>

        <td style="padding-left: 20px;padding-bottom: 20px;">

          <a href="/categories/<%= category.id %>">
            <img height="200px;" alt="" src="/assets/categories/<%= category.id %>.jpg" /></a>
          <p><a href="/categories/<%= category.id %>"><%= category.title %></a></p>
        </td>

        <% if i % 4 == 0 %>
            </tr>
            <tr>
        <% end %>
        <% i += 1 %>
    <% end %>
    </tr>

    </table>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<%= render :partial => "common/header"%>
<div style="text-align: center; margin-top: 30px;">
     <%= render partial: 'categories/photo', collection: @category.photos %>
    <br><br> <%= link_to 'Back', categories_path %>

</div>